name: anno-webext
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - &checkout
        uses: actions/checkout@v7
      - &setup-node
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run test:unit

  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        browser: [firefox, chromium]
    steps:
      - *checkout
      - *setup-node
      - run: npm ci
      - run: npx playwright install --with-deps ${{ matrix.browser }}
      - run: npm run test:e2e -- --project=${{ matrix.browser }}

  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - *checkout
      - *setup-node
      - run: npm ci
      - run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - *checkout
      - *setup-node
      - run: npm ci
      - run: npm run lint
